Feature/multi module setup
loodos/SampleComposeAndroid pull request #39
Opened 2023-10-10 11:46 UTC by merttoptas

2023-10-10 12:17 UTC, ahmeterloodos requested changes
- modellerdeki package name leri düzeltelim
- commentte olan satırları kaldıralım

2023-10-10 12:17 UTC, ahmeterloodos commented on app/build.gradle.kts
> +            enableUnitTestCoverage = true
bunu şimdilik kaldıralım

2023-10-10 12:17 UTC, ahmeterloodos commented on app/build.gradle.kts
> -        compose = true
diğer kod bloğundan kaldıralım buraya ekleyelim
 buildConfig = true

2023-10-10 12:17 UTC, ahmeterloodos commented on app/src/main/java/com/loodos/samplecomposeandroid/core/data/di/RemoteDataModule.kt
> +        return Retrofit.Builder().baseUrl("BuildConfig.BASE_URL")
commenti kaldıralım gradle daki BASE_UR li kullanalım

2023-10-10 12:17 UTC, ahmeterloodos commented on build-logic/convention/src/main/kotlin/FirebasePerfConventionPlugin.kt
> +                version = "1.4.1"
buradaki versiyonlamayı kataloğa taşıyabiliyor muyuz bakalım

2023-10-10 12:17 UTC, ahmeterloodos commented on core/common/build.gradle.kts
> +    implementation(libs.kotlinx.coroutines.android)
coroutines için build logicte convention plugin ihtiyacı olabilir diğer modellerde kullanacaktır nowin androidde bi bakalım

2023-10-11 09:34 UTC, merttoptas commented on build-logic/convention/src/main/kotlin/FirebasePerfConventionPlugin.kt
> +                version = "1.4.1"
Taşındı

2023-10-11 10:11 UTC, merttoptas commented on app/src/main/java/com/loodos/samplecomposeandroid/core/data/di/RemoteDataModule.kt
> +        return Retrofit.Builder().baseUrl("BuildConfig.BASE_URL")
eklendi

2023-10-11 10:47 UTC, murat-aydin-1 approved these changes

2023-10-12 13:16 UTC, ahmeterloodos approved these changes

2023-10-12 13:17 UTC, merged